---
title: "tidycensus"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("tidycensus")
#install.packages("tmap")
#install.packages("tmaptools")
#install.packages("sf")
#install.packages("tidyverse")
#install.packages("mapview")
library(tidycensus)
#library(tidyverse)
library(tmap)
library(tmaptools)
library(sf)
library(ggplot2)
library(dplyr)
library(mapview)
library(tigris)

```

```{r}
#free API key for census data acces

#saving the key for use in future session
census_api_key("302754c951c3654f732e85c0dafc3f20e9fa7267", install = TRUE, overwrite = TRUE) 

#saving the key in my .Renviron and can be accessed by Sys.getenv("CENSUS_API_KEY").
readRenviron("~/.Renviron")
```

```{r}
#create a daat frame of variables

#variables for 2017
v17 <- load_variables(2017, "acs5", cache = TRUE)

View(v17)
```


```{r}
median_household_income_all_counties <- get_acs(geography = "tract",
                         variables = "B19013_001", #median household income for all counties
                         state = "MA",
                         geometry = TRUE)
mapview(median_household_income_all_counties, zcol = "estimate")
```

```{r}
past_12_months_household_income_2017 <- get_acs(geography = "tract",
                         variables = "B19001_001", #HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2017 INFLATION-ADJUSTED DOLLARS)
                         state = "MA",
                         geometry = TRUE)
mapview(past_12_months_household_income_2017, zcol = "estimate")
```

```{r}
big_map <- mapview(past_12_months_household_income_2017, zcol = "estimate") +
  mapview(median_household_income_all_counties, zcol = "estimate")

big_map
```

Race:

```{r}
race_all <- get_acs(geography = "tract",
                    variables = "B02001_001", #race all
                    state = "MA",
                    county = "Hampden County",
                    geometry = TRUE)

mapview(race_all, zcol = "estimate")
```

```{r}
race_all <- get_acs(geography = "tract", #census tract-works for individual cities
                    variables = "B02001_001", #race all
                    state = "MA",
                    county = "Hampden County",
                    year = 2017,
                    geometry = TRUE,
                    keep_geo_vars = TRUE,
                    survey = "acs5")

mapview(race_all, zcol = "estimate")
```

```{r}
race_black <- get_acs(geography = "tract", #census tract-works for individual cities
                    variables = "B02001_003", #only african american
                    state = "MA",
                    county = "Hampden County",
                    year = 2018,
                    geometry = TRUE,
                    survey = "acs5") 



mapview(race_black, zcol = "estimate")
```

```{r}
race_white <- get_acs(geography = "tract", #census tract-works for individual cities
                    variables = "B02001_002", #only white
                    state = "MA",
                    county = "Hampden County",
                    year = 2018, #is also the defualt
                    geometry = TRUE,
                    survey = "acs5") 



mapview(race_white, zcol = "estimate")
```

```{r}
race_nativeAmerican <- get_acs(geography = "tract", #census tract-works for individual cities
                    variables = "B02001_004", #native american or alaskan native
                    state = "MA",
                    county = "Hampden County",
                    year = 2018,
                    geometry = TRUE,
                    keep_geo_vars = TRUE,
                    survey = "acs5") 



mapview(race_nativeAmerican, zcol = "estimate")
```

```{r}
race_asian <- get_acs(geography = "tract", #census tract-works for individual cities
                    variables = "B02001_005", #asian
                    state = "MA",
                    county = "Hampden County",
                    year = 2018,
                    geometry = TRUE,
                    keep_geo_vars = TRUE,
                    survey = "acs5") 



mapview(race_asian, zcol = "estimate")
```

```{r}
race_nativeHawaiian_pacificislander <- get_acs(geography = "tract", #census tract-works for individual cities
                    variables = "B02001_006", #native hawaiian or other pacific islander
                    state = "MA",
                    county = "Hampden County",
                    year = 2018,
                    geometry = TRUE,
                    keep_geo_vars = TRUE,
                    survey = "acs5") 



mapview(race_nativeHawaiian_pacificislander, zcol = "estimate")
```


```{r}
race_latino <- get_acs(geography = "tract", #census tract-works for individual cities
                    variables = "B03002_001", #hispanic or latino origin by race
                    state = "MA",
                    county = "Hampden County",
                    year = 2018,
                    geometry = TRUE,
                    keep_geo_vars = TRUE,
                    survey = "acs5") 



mapview(race_latino, zcol = "estimate")
```

```{r}
race_someOtherRaceAlone <- get_acs(geography = "tract", #census tract-works for individual cities
                    variables = "B02001_007", #some other race alone
                    state = "MA",
                    county = "Hampden County",
                    year = 2018,
                    geometry = TRUE,
                    keep_geo_vars = TRUE,
                    survey = "acs5") 



mapview(race_someOtherRaceAlone, zcol = "estimate")

```


```{r}
full_race_map <- mapview(race_someOtherRaceAlone, zcol = "estimate")+
  mapview(race_nativeHawaiian_pacificislander, zcol = "estimate") +
  mapview(race_asian, zcol = "estimate") + 
  mapview(race_black, zcol = "estimate") +
  mapview(race_latino, zcol = "estimate") +
  mapview(race_white, zcol = "estimate")

full_race_map
```


```{r}
racevars <- c(White = "B02001_002", 
              Black = "B02001_003", 
              Asian = "B02001_005", 
              Hispanic = "B03002_001",
              Native_american = "B02001_004",
              Native_hawaian = "B02001_006",
              someOtherRace = "B02001_007")

race <- get_acs(geography = "tract", variables = racevars, 
                  state = "MA", county = "Hampden County", geometry = TRUE,
                  summary_var = "B01003_001") 

race %>%
  mutate(pct = 100 * (estimate /summary_est)) %>% #moe in the df is margin of error
  ggplot(aes(fill = pct)) + #is a continuous scale so can't have discrete values
  facet_wrap(~variable) +
  geom_sf(color = NA) +
  coord_sf(crs = 26918) + 
  scale_fill_viridis_c()

#how to make this particular to the cities

race_latino %>%
  ggplot(aes(fill = estimate)) + 
  geom_sf(color = NA) + 
  coord_sf(crs = 26918) + 
  scale_fill_viridis_c(option = "magma") 


```

```{r}
trial1 <- get_acs(geography = "tract", #census tract-works for individual cities
                    variables = "B02001_002", #only white
                    state = "MA",
                    county = "Hampden County",
                    #city = "Holyoke",
                    year = 2018, #is also the defualt
                    geometry = TRUE,
                    survey = "acs5") 

mapview(trial1, zcol = "estimate")



trial2 <- get_acs(geography = "new england city and town area", #city and town area in new england
                  variables = "B02001_002", #only white
                 #state = "MA",
                  county = "Hampden County",
                    #city = "Holyoke",
                  year = 2018, #is also the defualt
                  geometry = TRUE,
                  survey = "acs5") 

mapview(trial2, zcol = "estimate")


#not state or county specific
trial3 <- get_acs(geography = "urban area", #census-defined urbanized areas
                  variables = "B02001_002", #only white
                  #state = "MA",
                  county = "Hampden County",
                    #city = "Holyoke",
                  year = 2018, #is also the defualt
                  geometry = TRUE,
                  survey = "acs5") 

mapview(trial3, zcol = "estimate")

#nope, bad option
trial4 <- get_acs(geography = "zcta", #zip code tabulation area, not even state specific
                  variables = "B02001_002", #only white
                  #state = "MA",
                    #county = "Hampden County",
                    #city = "Holyoke",
                  year = 2018, #is also the defualt
                  geometry = TRUE,
                  survey = "acs5") 

#to chache shape files for use in future sessions, set below to true
#options(tigris_use_chache = TRUE)

mapview(trial4, zcol = "estimate")

#might work, gives the 3 cities with others coloured in too
trial5 <- get_acs(geography = "place", #census designated place
                  variables = "B02001_002", #only white
                  state = "MA",
                  #county = "Hampden County",
                    #city = "Holyoke",
                  year = 2018, #is also the defualt
                  geometry = TRUE,
                  survey = "acs5") 

mapview(trial5, zcol = "estimate")

#lets get specific places

#freeze the frame into Holyoke Chicoppe and Springfield if specific places don't work
#but have one of specific places and one with general surrounding area to be able to show the disparity of resources and incomes
```




```{r}
#place and county geometries from tigris

ma_places <- tigris::places(state = "MA", cb = TRUE, class = "sf") %>%
  select(place_fips = GEOID, place_name = NAME)

ma_counties <- tigris::counties(state = "MA", cb = TRUE, class = "sf") %>%
  select(place_fips = GEOID, place_name = NAME)

#spatial join plces and counties to get counties that intersect places
#only slectt he county that has the largest overplace with each place
#View(ma_places)

#what is st_join()?
#View(hampden_places)
hampden_places <- st_join(ma_places, ma_counties, largest = FALSE) %>%
  filter(place_name.y == "Hampden")

#get acs data for all places in MA
ma_places_acs <- get_acs(
  geography = "places",
  variables = "B02001_002",
  state = "MA",
  year = 2017
)
#> getting data from the 2013-2017 5-year ACS

#filter for only places within hampden county, MA

ma_places_acs %>%
  filter(GEOID %in% hampden_places$place_fips)

#make map:

#install.packages("devtools")
#library(devtools)
#devtools::install_github("yutannihilation/ggsflabel")
#library(ggsflabel)

ggplot(hampden_places) +
  geom_sf(data = filter(ma_counties, place_name == "Hampden")) +
  geom_sf(color = "blue") +
  #ggsflabel::geom_sf_text_repel(aes(label = place_name.y), nudge_x = 0.03, nudge_y = -0.02)+ #what are the nudges?
  labs(title = "Census places in Hampden County, MA") +
  theme_void() #what does this do?
```

gives only chicopee without lat and long coord like in below
```{r}
ggplot(hampden_places) +
  geom_sf(data = filter(ma_places, place_name == "Chicopee")) +
  #geom_sf(color = "red") +
  #ggsflabel::geom_sf_text_repel(aes(label = place_name.y), nudge_x = 0.03, nudge_y = -0.02)+ #what are the nudges?
  #labs(title = "Census places in Hampden County, MA") +
  theme_void()
```


#individual geometry of each city
```{r}
holyoke <- ggplot(hampden_places)+
            geom_sf(data = filter(hampden_places, place_name.x == "Holyoke"))

chicopee <- ggplot(hampden_places)+
              geom_sf(data = filter(hampden_places, place_name.x == "Chicopee"))

springfield <- ggplot(hampden_places)+
                geom_sf(data = filter(hampden_places, place_name.x == "Springfield"))

holyoke
chicopee
springfield
```

```{r}
race_cities <- get_acs(geography = "tract", variables = racevars, 
                  state = "MA", county = "Hampden County", geometry = TRUE,
                  summary_var = "B01003_001") 

race %>%
  mutate(pct = 100 * (estimate /summary_est)) %>% #moe in the df is margin of error
  ggplot(aes(fill = pct)) + #is a continuous scale so can't have discrete values
  facet_wrap(~variable) +
  geom_sf(color = NA) +
  coord_sf(crs = 26918) + 
  scale_fill_viridis_c()
```

